language: php
php:
  - 5.6
  - hhvm

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mkdir -p build/logs
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer install --dev --no-interaction
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit -c app/phpunit.xml.dist

after_script:
 - php vendor/bin/coveralls


notifications:
  email:
    -  me@yupitszac.com