language: php
php:
  - 5.6

script: phpunit -c app/

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - phpunit


notifications:
  email:
    -  me@yupitszac.com