language: php
php:
  - 5.6

script: phpunit -c app/

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mkdir -p build/logs
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
notifications:
  email:
    -  me@yupitszac.com