# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    find_near_model:
            class: FreeGeo\ApiBundle\Model\FindNearModel
            arguments: ['@service_container']

    calculate_model:
        class: FreeGeo\ApiBundle\Model\CalculateModel
        arguments: ['@service_container']

    authenticate_model:
        class: FreeGeo\ApiBundle\Model\ApiAuthModel
        arguments: ['@service_container']

    detection_model:
        class: FreeGeo\ApiBundle\Model\DetectionModel
        arguments: ['@service_container']